### ISSUE TITLE
ActiveRecord::DangerousAttributeError (deleted? is defined by ActiveRecord)

### ISSUE THREAD

**Issue by rthbound** [JackDanger/permanent_records#38]
> Started GET "/users/sign_in" for 127.0.0.1 at 2014-10-08 13:07:41 -0500
> Processing by Devise::SessionsController#new as HTML
> Completed 500 Internal Server Error in 29.5ms
>
> ActiveRecord::DangerousAttributeError (deleted? is defined by ActiveRecord):
>   activerecord (3.2.18) lib/active_record/attribute_methods.rb:91:in `instance_method_already_implemented?'

Grep shows that `permanent_records` is the only library containing a `def deleted?`. I have confirmed that uninstalling `permanent_records` alleviates the error.

This error is new to me and at the moment is only happening in my development environment. I've deployed my most recent changes, and the error does not occur in either staging or production environments.  IF I run the application locally in production mode, then the error DOES occur.

I'm pretty perplexed by this. At the moment I'm considering forking this gem and not defining the methods AR is complaining about. I would greatly appreciate any insight that any of you can share.

**Comment by nixme** [comment]
You're database table has a field named `deleted` instead of `deleted_at` and so AR defines a `deleted?` method telling you whether the attribute is not-`nil`

**Comment by rthbound** [comment]
Unfortunately, no `deleted` columns. I have `deleted_at` and `deleted_on`, but have never had a `deleted`.

I have (since reporting this issue) removed the gem -- I just didn't have the time or bandwidth to suss out the root of the problem.

Thanks @nixme for the suggestion.  I'll leave it to the maintainer to decide whether this issue should be closed or not.

**Comment by JackDanger** [comment]
@rthbound I'm sorry the gem caused you trouble. If it happened only in development then I suspect you could reinstall the gem, clone your production schema to development, and it would work just fine locally. There aren't any environment-specific parts of the `permanent_records` gem.
But if you don't need it then definitely remove it! The fewer dependencies the better.
