### ISSUE TITLE
#destroy not returning false like AR does with before_destroy callbacks

### ISSUE THREAD

**Issue by hughevans** [JackDanger/permanent_records#47]
There’s a bit of an inconsistency with the standard AR `#destroy` and PermanentRecords’ version:

> There's a series of callbacks associated with destroy. If the before_destroy callback return false the action is cancelled and destroy returns false. See ActiveRecord::Callbacks for further details.

From http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-destroy

Is there a reason not to replicate this? PermanentRecords still returns the object, only it’s not deleted, so you have to `record.destroy && record.deleted?` to know.

I had to change my failing specs from:

```
     Failure/Error: expect(subject.destroy).to eql(false)

       expected: false
            got: #<Record id: 1, deleted_at: nil>
```

To:

``` ruby
expect { subject.destroy }.to_not change { subject.deleted? }
```

I also had to change all my controllers that had `if @record.destroy` conditionals.

Not a huge issue, but I think AR consistency here is probably worthwhile.

**Comment by hughevans** [comment]
This behaviour also breaks `#destroy!`

```
Failure/Error: expect { subject.destroy! }.to raise_error(ActiveRecord::RecordNotDestroyed)
       expected ActiveRecord::RecordNotDestroyed but nothing was raised
```

``` ruby
# File activerecord/lib/active_record/persistence.rb, line 184
def destroy!
  destroy || raise(RecordNotDestroyed.new("Failed to destroy the record", self))
end
```

**Comment by JackDanger** [comment]
@hughevans Thanks for this, I think you're absolutely right. Do you mind taking a stab at either adding a (failing) test for the correct behavior or implementing the fix (or both)? If you get it started then I or other contributors can help you get it over the finish line.

**Comment by hughevans** [comment]
Thanks. I guess this is a potentially API breaking change for people who may have relied on this behaviour. A 4.x release?

**Comment by JackDanger** [comment]
@hughevans Good idea. Do you mind making a PR to adjust the README? I'll cut a 4.0 release and add you as an author. Thanks!
