### ISSUE TITLE
Errors with Rails 4.2.5

### ISSUE THREAD

**Issue by billhorsman** [JackDanger/permanent_records#53]
Hi Jack!

I'm getting 32 failures when running the tests for this project with Rails 4.2.5. They pass with Rails 4.2.4 and fail with Rails 4.2.5.rc1 and later. For instance:

```
PermanentRecords#revive with dependent records as default scope with :has_one cardinality revives them
     Failure/Error: let!(:record) { hole.destroy }
     NoMethodError:
       undefined method `attributes' for false:FalseClass
     # ./lib/permanent_records.rb:92:in `destroy_with_permanent_records'
     # ./lib/permanent_records.rb:47:in `block in destroy'
     # ./lib/permanent_records.rb:43:in `destroy'
     # ./spec/permanent_records_spec.rb:227:in `block (3 levels) in <top (required)>'
```

In my own code, this causes a problem when I use the `after_destroy` callback. The `before_destroy` callback works fine. 

It doesn't seem to have been caused by a recent changed to this project but nothing leaps out at me in in the changes between [Rails 4.2.4 and 4.2.5.rc1](https://github.com/rails/rails/compare/v4.2.4...v4.2.5.rc1).

**Comment by gsmetal** [comment]
+1. Version 3.3.0 does not work for now. Version 4.0.0 is not installing due to dependencies of activerecord (4.2.0).

**Comment by orenyk** [comment]
+1 to @gsmetal's comment about the dependency conflict.

**Comment by Preacher** [comment]
I edited Version 4.0.0 locally to install with Rails 4.2.5 and I'm experiencing the same error there.

As of now, I had to downgrade to Rails 4.2.4.

**Comment by JackDanger** [comment]
The internal API to callbacks changed slightly. Apologies for the broken code! This is now fixed on master and I've pushed a gem version 4.1.0 with a fix. Thanks!

**Comment by Preacher** [comment]
Works great. Thanks a bunch!!

**Comment by amyp1** [comment]
Thanks

**Comment by billhorsman** [comment]
Thanks Jack. That works fine.
