### ISSUE TITLE
Test suite is failing?! Need the right command

### ISSUE THREAD

**Issue by joel** [JackDanger/permanent_records#55]
Hi, I don't know how is suitable to lunch your test suite, I looked on [Travis-CI your last build](https://travis-ci.org/JackDanger/permanent_records/jobs/75308278) and I saw is ok but when I try to start test with the same commands : 

```
export AR_TEST_VERSION=4.2.0
bundle exec rake
```

test suite still failing with or without AR_TEST_VERSION, and whatever I tried.... So please leave me the right command.

I found some cases with `permanent_records` don't play well, I want to give you some specs to point these problems but I need to start your test suite for that.

Thanks

**Comment by mherold** [comment]
Hi joel, the command seems correct to me. What's the ruby version you're using, and maybe one or two sample failures?

**Comment by joel** [comment]
@mherold it is! Sorry I played wrongly with export bash variable, maybe adding a default one?
