### ISSUE TITLE
CounterCache support

### ISSUE THREAD

**Issue by drakmail** [JackDanger/permanent_records#73]
Could I implement an update of counter caches in `destroy` / `revive` methods and send a pull request with changes? Or there are exists another better ways to deal with counting of `not_deleted` items?

**Comment by JackDanger** [comment]
Please do! I haven't used counter caches in my apps so I didn't think to incorporate them here. I'd love to see your proposal in code for how to address a counter cache on an association full of permanent records.

**Comment by drakmail** [comment]
Awesome! Created #74

**Comment by drakmail** [comment]
@JackDanger any thoughts?

**Comment by JackDanger** [comment]
Excellent work, @drakmail. I'll push a new gem now.

**Comment by JackDanger** [comment]
Gem 4.1.6 pushed to rubygems. Thanks for your contribution!
