### ISSUE TITLE
Counter cache doesn't work with polymorphic association

### ISSUE THREAD

**Issue by n-rodriguez** [JackDanger/permanent_records#77]
It breaks [here](https://github.com/JackDanger/permanent_records/commit/db72028d2e7c6f4ed9646277dbf7a9607c28ca04#diff-3f1f490733849c83be61164ad709612dR111) with ```NameError: uninitialized constant Commentable```

**Comment by n-rodriguez** [comment]
The quick and dirty patch (in ```config/initializers/permanent_records.rb```) :

```
require 'permanent_records'

# Patch PermanentRecords to not check for counter_cache on polymorphic association

module PermanentRecordsPatch
  def self.included(base)
    base.send(:include, InstanceMethods)
    base.class_eval do
      alias_method_chain :each_counter_cache, :patch
    end
  end

  module InstanceMethods

    def each_counter_cache_with_patch
      _reflections.each do |name, reflection|
        next if reflection.polymorphic?
        associated_class = association(name).reflection.class_name.constantize
        next unless reflection.belongs_to? && reflection.counter_cache_column
        yield(associated_class,
              reflection.counter_cache_column,
              send(reflection.foreign_key))
      end
    end

  end
end

unless PermanentRecords::ActiveRecord.included_modules.include?(PermanentRecordsPatch)
  PermanentRecords::ActiveRecord.send(:include, PermanentRecordsPatch)
end
```

**Comment by drakmail** [comment]
Oh, I'll fix it tomorrow

**Comment by n-rodriguez** [comment]
> Oh, I'll fix it tomorrow

Ok. As I said this is a quick and dirty patch. I don't know if counter_cache works with polymorphic associations. By looking at the code as it's written I would say no. 
```
associated_class = association(name).reflection.class_name.constantize
```

But maybe it's possible to get all polymorphic classes (classes which are commentable for instance).

**Comment by drakmail** [comment]
Created a pull request that should fix the issue (regarding to specs). Could you check gem version from github (`gem 'permanent_records', github: 'drakmail/permanent_records', branch: 'polymorphic_counter_cache'`?

**Comment by JackDanger** [comment]
@drakmail I've added you as a collaborator on `permanent_records` so please do what you feel is best in getting this fix merged. If we land changes on master I'll bump the version and re-publish the gem.

**Comment by n-rodriguez** [comment]
@drakmail : I've switched to your branch and run my tests and it works.
