### ISSUE TITLE
Version number is not consistent

### ISSUE THREAD

**Issue by n-rodriguez** [JackDanger/permanent_records#80]
On Github master branch the version is 4.1.5
On Rubygem the version is 4.1.6 (https://rubygems.org/gems/permanent_records/)

**Comment by JackDanger** [comment]
Apologies for this! I left unpushed commits on my laptop. This is a classic example of not automating my workflow and I've fixed it with a new Rake task. It won't happen again. Thanks for pointing this out!

There's now a version 4.1.7 that has everything on master (and vice versa).
