### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by arizz96** [JackDanger/permanent_records#98]
Hi,
I see that master release isn't aligned with 4.2.7 version available from RubyGems. When a new version will be release?
Also, I think that maintain the Release tab up-to-date can be useful to track changes.

Thank you!

**Comment by mherold** [comment]
@JackDanger Could you please bump the version to 4.2.8, tag it, and release? 

After that @msalzburg and I might have a look at full Rails 5.x compatibility and any existing PRs regarding Rails 5.x. We might want to drop compatibility with some older/unsupported Ruby/Rails versions then (which would imply releasing a new major version afterwards).

**Comment by JackDanger** [comment]
@mherold I've bumped the version and published 4.2.8 (including git tags, thanks!)

**Comment by JackDanger** [comment]
note to self: Get this publishing automatically via GitHub Actions
